/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokedexAppLayoutRouteImport } from './routes/pokedex/_appLayout'
import { Route as PokedexappIndexRouteImport } from './routes/pokedex/(app)/index'
import { Route as PokedexappPokemonIdRouteImport } from './routes/pokedex/(app)/$pokemonId'

const PokedexRouteImport = createFileRoute('/pokedex')()

const PokedexRoute = PokedexRouteImport.update({
  id: '/pokedex',
  path: '/pokedex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexAppLayoutRoute = PokedexAppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => PokedexRoute,
} as any)
const PokedexappIndexRoute = PokedexappIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => PokedexRoute,
} as any)
const PokedexappPokemonIdRoute = PokedexappPokemonIdRouteImport.update({
  id: '/(app)/$pokemonId',
  path: '/$pokemonId',
  getParentRoute: () => PokedexRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexAppLayoutRoute
  '/pokedex/$pokemonId': typeof PokedexappPokemonIdRoute
  '/pokedex/': typeof PokedexappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexappIndexRoute
  '/pokedex/$pokemonId': typeof PokedexappPokemonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexRouteWithChildren
  '/pokedex/_appLayout': typeof PokedexAppLayoutRoute
  '/pokedex/(app)/$pokemonId': typeof PokedexappPokemonIdRoute
  '/pokedex/(app)/': typeof PokedexappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokedex' | '/pokedex/$pokemonId' | '/pokedex/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokedex' | '/pokedex/$pokemonId'
  id:
    | '__root__'
    | '/'
    | '/pokedex'
    | '/pokedex/_appLayout'
    | '/pokedex/(app)/$pokemonId'
    | '/pokedex/(app)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokedexRoute: typeof PokedexRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokedex': {
      id: '/pokedex'
      path: '/pokedex'
      fullPath: '/pokedex'
      preLoaderRoute: typeof PokedexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex/_appLayout': {
      id: '/pokedex/_appLayout'
      path: '/pokedex'
      fullPath: '/pokedex'
      preLoaderRoute: typeof PokedexAppLayoutRouteImport
      parentRoute: typeof PokedexRoute
    }
    '/pokedex/(app)/': {
      id: '/pokedex/(app)/'
      path: '/'
      fullPath: '/pokedex/'
      preLoaderRoute: typeof PokedexappIndexRouteImport
      parentRoute: typeof PokedexRoute
    }
    '/pokedex/(app)/$pokemonId': {
      id: '/pokedex/(app)/$pokemonId'
      path: '/$pokemonId'
      fullPath: '/pokedex/$pokemonId'
      preLoaderRoute: typeof PokedexappPokemonIdRouteImport
      parentRoute: typeof PokedexRoute
    }
  }
}

interface PokedexRouteChildren {
  PokedexAppLayoutRoute: typeof PokedexAppLayoutRoute
  PokedexappPokemonIdRoute: typeof PokedexappPokemonIdRoute
  PokedexappIndexRoute: typeof PokedexappIndexRoute
}

const PokedexRouteChildren: PokedexRouteChildren = {
  PokedexAppLayoutRoute: PokedexAppLayoutRoute,
  PokedexappPokemonIdRoute: PokedexappPokemonIdRoute,
  PokedexappIndexRoute: PokedexappIndexRoute,
}

const PokedexRouteWithChildren =
  PokedexRoute._addFileChildren(PokedexRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokedexRoute: PokedexRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
